### ISSUE TITLE
which version libvlc is used?

### ISSUE THREAD

**Issue by umjammer** [Nick1st/FancyVideo-API-1.18#1]
hi, i'm tying to apply this mod to macos.
i saw you bundle windows libvlc in this project.

vlcj said that use libvlc 4.0.0+ for vlcj.
i tried to apply 3 nightly builds of version 4.
(28-apr-22, 01-apr-22, 01-nov-21)
but all of those don't work and get an error.

could you tell me which version (date) of libvlc do you use?

**Comment by Nick1st** [comment]
Hello,
I'm sorry that you're having problems with my lib. The lib should work with all of the prereleases (at least it does on windows). Can you please give me more information on what you are doing? I'd need the following information:

- Minecraft version
- Modloader and Version
- OS Build and Arch
- Path and version of all vlc installs on the system


I also need:

- latest.log
- debug.log (if it's available)
- vlc.log

Nick1st

**Comment by umjammer** [comment]
i'm in testing vlcj sample before modding.
this is not mod problem but just vlcj.
so i asked you to tell me **only the libvlc version**.

--
first i used `01-nov-21` nightly version which is around the day of last committing of vlcj about macos.
but i got follows.
```
Error looking up function 'libvlc_media_get_filestat': dlsym(0x7f9dbb52a040, libvlc_media_get_filestat): symbol not found
Exception in thread "main" uk.co.caprica.vlcj.factory.NativeLibraryMappingException: Failed to properly initialise the native library
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:184)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at vlcj.VideoEngineCallbackDemo.<init>(VideoEngineCallbackDemo.java:120)
	at vlcj.VideoEngineCallbackDemo.main(VideoEngineCallbackDemo.java:329)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181)
	... 4 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Error looking up function 'libvlc_media_get_filestat': dlsym(0x7f9dbb52a040, libvlc_media_get_filestat): symbol not found [in thread "main"]
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
	at com.sun.jna.Native.register(Native.java:1904)
	at com.sun.jna.Native.register(Native.java:1775)
	at com.sun.jna.Native.register(Native.java:1493)
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:110)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryLoadingLibrary(NativeDiscovery.java:187)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:118)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:176)
	... 4 more
```
i looked into the vlc git, then i found the function name modification at [here](https://code.videolan.org/videolan/vlc/-/commit/8d095dbf96d8992e0da21d7912a5b61571af719e)

so we should use the version after the modification.

second i tried the newest version `28-apr-22`, but i got
```
Assertion failed: (param != NULL), function config_GetPsz, file ../../src/config/core.c, line 102.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
(this occurs every [sample](https://github.com/caprica/vlcj-examples) which i tested)

i looked into the vlc git again, and searched about `config_GetPsz`.
but the result was [like that](https://code.videolan.org/search?group_id=9&project_id=435&repository_ref=master&scope=commits&search=config_GetPsz&snippets=false)
last commit was 4y ago.

i am ??? now.
so give me **your libvlc version**, thanks

**Comment by Nick1st** [comment]
You haven't answered my questions. Anyway, to answer yours: I don't have one. I daily pull the latest build.
Assertion failed normally means a library can't be accessed, that's all I know. If you think it's a VLCJ issue then ask caprica.

**Comment by Nick1st** [comment]
Closing this for issuer not responding
